name: Build
description: Build mariadb image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  workdir:
    description: working directory
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
  alpine:
    description: alpine version
    required: false
    default: '3.17'
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      MARIADB_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
      ALPINE_VER: ${{ inputs.alpine }}
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
    working-directory: ${{ inputs.workdir }}
