name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.13.3
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  mariadb-110:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '11.0.4'
        tags: '11.0,11,latest'
        workdir: 11
        #        platform: linux/amd64,linux/arm64
        platform: linux/amd64
  mariadb-1011:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '10.11.6'
        tags: '10.11,10'
        workdir: 10
        #        platform: linux/amd64,linux/arm64
        platform: linux/amd64
  mariadb-1010:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '10.10.7'
        tags: '10.10'
        workdir: 10
        #        platform: linux/amd64,linux/arm64
        platform: linux/amd64
  mariadb-109:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '10.9.8'
        tags: '10.9'
        workdir: 10
        #        platform: linux/amd64,linux/arm64
        platform: linux/amd64
  mariadb-106:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '10.6.16'
        tags: '10.6'
        workdir: 10
#        platform: linux/amd64,linux/arm64
        platform: linux/amd64
  mariadb-105:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '10.5.23'
        tags: '10.5'
        workdir: 10
#        platform: linux/amd64,linux/arm64
        platform: linux/amd64
  mariadb-104:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '10.4.31'
        tags: '10.4'
        workdir: 10
#        platform: linux/amd64,linux/arm64
        platform: linux/amd64
        alpine: '3.15'
